language: c
dist: bionic

env:
    - SMVERSION=1.8
    - SMVERSION=1.9
    - SMVERSION=1.10
    - SMVERSION=1.11

matrix:
    fast_finish: true
    allow_failures:
    - env: SMVERSION=1.8
    - env: SMVERSION=1.9

before_install:
    - sudo apt-get update
    - sudo apt-get install gcc-multilib
    - sudo apt-get install lib32stdc++6

before_script:
    # Make directory for SourceMod
    - mkdir -p am/sm
    - cd am/sm
    - wget -q "http://www.sourcemod.net/latest.php?version=$SMVERSION&os=linux" -O sourcemod.tar.gz
    - tar -xzf sourcemod.tar.gz

    # Download git-helper script for generating defines, start him.
    - wget -q https://raw.githubusercontent.com/CrazyHackGUT/sm-plugins/master/git.sh
    - chmod +x git.sh
    - ./git.sh > addons/sourcemod/scripting/AutoDemo.git.sp

    # Go to scripting directory, exec chmod
    - cd addons/sourcemod/scripting
    - chmod +x spcomp
    - chmod +x compile.sh

    # Copy plugins, download dependencies
    - cp -Rf ${TRAVIS_BUILD_DIR}/scripting/* ./
    - mkdir -p include/ripext
    - mkdir -p AutoDemo/optional
    - curl "https://raw.githubusercontent.com/ErikMinekus/sm-ripext/master/pawn/scripting/include/ripext.inc" -o include/ripext.inc
    - curl "https://raw.githubusercontent.com/ErikMinekus/sm-ripext/master/pawn/scripting/include/ripext/http.inc" -o include/ripext/http.inc
    - curl "https://raw.githubusercontent.com/ErikMinekus/sm-ripext/master/pawn/scripting/include/ripext/json.inc" -o include/ripext/json.inc
    - curl "https://raw.githubusercontent.com/peace-maker/sourcetvmanager/master/sourcetvmanager.inc" -o include/sourcetvmanager.inc

    # For FTP Uploading...
    # - curl "https://raw.githubusercontent.com/thraaawn/SMbz2/master/pawn/scripting/include/bzip2.inc" -o include/bzip2.inc
    # - curl "https://raw.githubusercontent.com/JoinedSenses/SourceMod-IncludeLibrary/master/include/cURL.inc" -o include/cURL.inc
    # - curl "https://raw.githubusercontent.com/JoinedSenses/SourceMod-IncludeLibrary/master/include/cURL_header.inc" -o include/cURL_header.inc

script:
    - ./spcomp $COMPILER_PARAMS AutoDemo.git.sp AutoDemo.sp -E -oAutoDemo/Core
    - ./spcomp $COMPILER_PARAMS AutoDemo.git.sp AutoDemo_EventManager.sp -E -oAutoDemo/EventManager
    - ./spcomp $COMPILER_PARAMS AutoDemo.git.sp AutoDemo_TF2.sp -E -oAutoDemo/optional/TF2
    - ./spcomp $COMPILER_PARAMS AutoDemo.git.sp AutoDemo_Notify.sp -E -oAutoDemo/optional/ChatNotifications
    # - ./spcomp $COMPILER_PARAMS AutoDemo.git.sp AutoDemo_FTPUpload.sp -E -oAutoDemo/optional/FTPUpload

before_deploy:
    - export FILENAME=sm_autodemo.${TRAVIS_COMMIT:0:7}.${SMVERSION}.tar.gz
    - export PACKAGE_PATH=${TRAVIS_BUILD_DIR}/../package
    - mkdir -p $PACKAGE_PATH/addons/sourcemod/{gamedata,data/demos,scripting,plugins/AutoDemo,translations}
    - cp -Rf $TRAVIS_BUILD_DIR/scripting/* $PACKAGE_PATH/addons/sourcemod/scripting/
    - cp -Rf $TRAVIS_BUILD_DIR/gamedata/* $PACKAGE_PATH/addons/sourcemod/gamedata/
    - cp -Rf AutoDemo/* $PACKAGE_PATH/addons/sourcemod/plugins/AutoDemo/
    - cp -Rf $TRAVIS_BUILD_DIR/translations/* $PACKAGE_PATH/addons/sourcemod/translations/
    - cd $TRAVIS_BUILD_DIR
    - tar -cvf ../${FILENAME} ${PACKAGE_PATH}

deploy:
    - provider: script
      skip_cleanup: true
      script: curl "${API_URL}?secret_key=${API_KEY}&tags=SourceMod%20${SMVERSION}" -F "artifact=@./../${FILENAME}"
